[workspace]
members = [
	"bin/node-template",
	"bin/node/cli",
	"bin/node/executor",
	"bin/node/primitives",
	"bin/node/rpc",
	"bin/node/rpc-client",
	"bin/node/runtime",
	"bin/node/testing",
	"bin/subkey",
	"client/authority-discovery",
	"client/chain-spec",
	"client/chain-spec/derive",
	"client/cli",
	"client/client",
	"client/client/db",
	"client/client/header-metadata",
	"client/consensus/aura",
	"client/consensus/babe",
	"client/consensus/pow",
	"client/consensus/rhd",
	"client/consensus/slots",
	"client/consensus/uncles",
	"client/executor",
	"client/executor/runtime-test",
	"client/finality-grandpa",
	"client/keyring",
	"client/keystore",
	"client/network",
	"client/panic-handler",
	"client/rpc",
	"client/rpc-servers",
	"client/service",
	"client/service/test",
	"client/state-machine",
	"client/telemetry",
	"client/transaction-pool",
	"client/transaction-pool/graph",
	"client/trie",
	"client/utils/fork-tree",
	"client/utils/wasm-builder",
	"client/utils/wasm-builder-runner",
	"paint/assets",
	"paint/aura",
	"paint/authority-discovery",
	"paint/authorship",
	"paint/balances",
	"paint/collective",
	"paint/contracts",
	"paint/contracts/rpc",
	"paint/democracy",
	"paint/elections",
	"paint/elections-phragmen",
	"paint/evm",
	"paint/example",
	"paint/executive",
	"paint/finality-tracker",
	"paint/generic-asset",
	"paint/grandpa",
	"paint/im-online",
	"paint/indices",
	"paint/membership",
	"paint/metadata",
	"paint/nicks",
	"paint/offences",
	"paint/randomness-collective-flip",
	"paint/scored-pool",
	"paint/session",
	"paint/staking",
	"paint/staking/reward-curve",
	"paint/sudo",
	"paint/support",
	"paint/support/procedural",
	"paint/support/procedural/tools",
	"paint/support/procedural/tools/derive",
	"paint/support/rpc",
	"paint/support/test",
	"paint/system",
	"paint/system/rpc",
	"paint/timestamp",
	"paint/transaction-payment",
	"paint/transaction-payment/rpc",
	"paint/treasury",
	"paint/utility",
	"primitives/application-crypto",
	"primitives/consensus/common",
	"primitives/core",
	"primitives/externalities",
	"primitives/finality-grandpa",
	"primitives/inherents",
	"primitives/rpc",
	"primitives/runtime-interface",
	"primitives/runtime-interface/proc-macro",
	"primitives/runtime-interface/test-wasm",
	"primitives/serializer",
	"primitives/session",
	"primitives/sr-api-macros",
	"primitives/sr-arithmetic",
	"primitives/sr-io",
	"primitives/sr-primitives",
	"primitives/sr-sandbox",
	"primitives/sr-staking-primitives",
	"primitives/sr-std",
	"primitives/sr-version",
	"primitives/wasm-interface",
	"test/utils/chain-spec-builder",
	"test/utils/client",
	"test/utils/runtime",
	"test/utils/runtime/client",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
