[package]
name = "substrate-session"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", path = "../../client/client", default-features = false }
rstd = { package = "sr-std", path = "../sr-std", default-features = false }
sr-primitives = { path = "../sr-primitives", optional = true }
primitives = { package = "substrate-primitives", path = "../core", optional = true }

[features]
default = [ "std" ]
std = [ "client/std", "rstd/std", "sr-primitives", "primitives" ]
