[package]
name = "node-runtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.102", optional = true }

# primitives
babe-primitives = { package = "substrate-consensus-babe-primitives", path = "../../../primitives/consensus/babe", default-features = false }
node-primitives = { path = "../primitives", default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", path = "../../../primitives/offchain", default-features = false }
primitives = { package = "substrate-primitives",  path = "../../../primitives/core", default-features = false }
sr-primitives = { path = "../../../primitives/sr-primitives", default-features = false }
sr-staking-primitives = { path = "../../../primitives/sr-staking-primitives", default-features = false }

# core dependencies
client = { package = "substrate-client", path = "../../../client/", default-features = false }
rstd = { package = "sr-std", path = "../../../primitives/sr-std", default-features = false }
version = { package = "sr-version", path = "../../../primitives/sr-version", default-features = false }
substrate-session = { path = "../../../primitives/session", default-features = false }
substrate-keyring = { path = "../../../client/keyring", optional = true }

# srml dependencies
authorship = { package = "srml-authorship", path = "../../../paint/authorship", default-features = false }
babe = { package = "srml-babe", path = "../../../paint/babe", default-features = false }
balances = { package = "srml-balances", path = "../../../paint/balances", default-features = false }
collective = { package = "srml-collective", path = "../../../paint/collective", default-features = false }
contracts = { package = "srml-contracts", path = "../../../paint/contracts", default-features = false }
contracts-rpc-runtime-api = { package = "srml-contracts-rpc-runtime-api", path = "../../../paint/contracts/rpc/runtime-api/", default-features = false }
democracy = { package = "srml-democracy", path = "../../../paint/democracy", default-features = false }
elections-phragmen = { package = "srml-elections-phragmen", path = "../../../paint/elections-phragmen", default-features = false }
executive = { package = "srml-executive", path = "../../../paint/executive", default-features = false }
finality-tracker = { package = "srml-finality-tracker", path = "../../../paint/finality-tracker", default-features = false }
grandpa = { package = "srml-grandpa", path = "../../../paint/grandpa", default-features = false }
im-online = { package = "srml-im-online", path = "../../../paint/im-online", default-features = false }
indices = { package = "srml-indices", path = "../../../paint/indices", default-features = false }
membership = { package = "srml-membership", path = "../../../paint/membership", default-features = false }
nicks = { package = "srml-nicks", path = "../../../paint/nicks", default-features = false }
offences = { package = "srml-offences", path = "../../../paint/offences", default-features = false }
randomness-collective-flip = { package = "srml-randomness-collective-flip", path = "../../../paint/randomness-collective-flip", default-features = false }
session = { package = "srml-session", path = "../../../paint/session", default-features = false, features = ["historical"] }
staking = { package = "srml-staking", path = "../../../paint/staking", default-features = false }
srml-staking-reward-curve = { path = "../../../paint/staking/reward-curve"}
sudo = { package = "srml-sudo", path = "../../../paint/sudo", default-features = false }
support = { package = "srml-support", path = "../../../paint/support", default-features = false }
system = { package = "srml-system", path = "../../../paint/system", default-features = false }
system-rpc-runtime-api = { package = "srml-system-rpc-runtime-api", path = "../../../paint/system/rpc/runtime-api/", default-features = false }
timestamp = { package = "srml-timestamp", path = "../../../paint/timestamp", default-features = false }
treasury = { package = "srml-treasury", path = "../../../paint/treasury", default-features = false }
utility = { package = "srml-utility", path = "../../../paint/utility", default-features = false }
transaction-payment = { package = "srml-transaction-payment", path = "../../../paint/transaction-payment", default-features = false }
transaction-payment-rpc-runtime-api = { package = "srml-transaction-payment-rpc-runtime-api", path = "../../../paint/transaction-payment/rpc/runtime-api/", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4", path = "../../../client/utils/wasm-builder-runner" }

[dev-dependencies]
runtime_io = { package = "sr-io", path = "../../../primitives/sr-io" }

[features]
default = ["std"]
std = [
	"authorship/std",
	"babe-primitives/std",
	"babe/std",
	"balances/std",
	"codec/std",
	"collective/std",
	"contracts/std",
	"contracts-rpc-runtime-api/std",
	"democracy/std",
	"elections-phragmen/std",
	"executive/std",
	"finality-tracker/std",
	"grandpa/std",
	"im-online/std",
	"indices/std",
	"membership/std",
	"nicks/std",
	"node-primitives/std",
	"offchain-primitives/std",
	"offences/std",
	"primitives/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"rustc-hex",
	"safe-mix/std",
	"serde",
	"session/std",
	"sr-primitives/std",
	"sr-staking-primitives/std",
	"staking/std",
	"substrate-keyring",
	"substrate-session/std",
	"sudo/std",
	"support/std",
	"system/std",
	"system-rpc-runtime-api/std",
	"timestamp/std",
	"treasury/std",
	"utility/std",
	"transaction-payment/std",
	"transaction-payment-rpc-runtime-api/std",
	"version/std",
]
