[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "1.0.0" }
runtime_io = { package = "sr-io", path = "../../../primitives/sr-io" }
state_machine = { package = "substrate-state-machine", path = "../../../client/state-machine" }
substrate-executor = { path = "../../../client/executor" }
primitives = { package = "substrate-primitives", path = "../../../primitives/core" }
trie = { package = "substrate-trie", path = "../../../client/trie" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
node-testing = { path = "../testing" }
test-client = { package = "substrate-test-client", path = "../../../test/utils/client" }
sr-primitives = { path = "../../../primitives/sr-primitives" }
runtime_support = { package = "srml-support", path = "../../../paint/support" }
balances = { package = "srml-balances", path = "../../../paint/balances" }
transaction-payment = { package = "srml-transaction-payment", path = "../../../paint/transaction-payment" }
session = { package = "srml-session", path = "../../../paint/session" }
system = { package = "srml-system", path = "../../../paint/system" }
timestamp = { package = "srml-timestamp", path = "../../../paint/timestamp" }
treasury = { package = "srml-treasury", path = "../../../paint/treasury" }
contracts = { package = "srml-contracts", path = "../../../paint/contracts" }
grandpa = { package = "srml-grandpa", path = "../../../paint/grandpa" }
indices = { package = "srml-indices", path = "../../../paint/indices" }
wabt = "0.9.2"
criterion = "0.3.0"

[features]
wasmtime = [
    "substrate-executor/wasmtime",
]
stress-test = []

[[bench]]
name = "bench"
harness = false

