[package]
name = "node-template-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
safe-mix = { version = "1.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", path = "../../../primitives/sr-std", default_features = false }
runtime-io = { package = "sr-io", path = "../../../primitives/sr-io", default_features = false }
version = { package = "sr-version", path = "../../../primitives/sr-version", default_features = false }
support = { package = "srml-support", path = "../../../paint/support", default_features = false }
primitives = { package = "substrate-primitives", path = "../../../primitives/core", default_features = false }
substrate-session = { path = "../../../primitives/session", default-features = false }
balances = { package = "srml-balances", path = "../../../paint/balances", default_features = false }
aura = { package = "srml-aura", path = "../../../paint/aura", default_features = false }
aura-primitives = { package = "substrate-consensus-aura-primitives", path = "../../../primitives/consensus/aura", default_features = false }
grandpa = { package = "srml-grandpa", path = "../../../paint/grandpa", default_features = false }
executive = { package = "srml-executive", path = "../../../paint/executive", default_features = false }
indices = { package = "srml-indices", path = "../../../paint/indices", default_features = false }
randomness-collective-flip = { package = "srml-randomness-collective-flip", path = "../../../paint/randomness-collective-flip", default_features = false }
system = { package = "srml-system", path = "../../../paint/system", default_features = false }
timestamp = { package = "srml-timestamp", path = "../../../paint/timestamp", default_features = false }
sudo = { package = "srml-sudo", path = "../../../paint/sudo", default_features = false }
transaction-payment = { package = "srml-transaction-payment", path = "../../../paint/transaction-payment", default_features = false }
sr-primitives = { path = "../../../primitives/sr-primitives", default_features = false }
client = { package = "substrate-client", path = "../../../client/", default_features = false }
offchain-primitives = { package = "substrate-offchain-primitives", path = "../../../primitives/offchain", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	"codec/std",
	"rstd/std",
	"runtime-io/std",
	"support/std",
	"balances/std",
	"aura/std",
	"aura-primitives/std",
	"grandpa/std",
	"executive/std",
	"indices/std",
	"primitives/std",
	"sr-primitives/std",
	"randomness-collective-flip/std",
	"system/std",
	"timestamp/std",
	"sudo/std",
	"transaction-payment/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"offchain-primitives/std",
	"substrate-session/std",
]
